### ISSUE TITLE
NameError: global name 'conduct' is not defined

### ISSUE THREAD

**Issue by hackerzone85** [crook/yum-axelget#9]
when i am trying to install a pkg with  all plugins, i got following error:

``` javascript
Total download size: 435 M
Installed size: 1.6 G
Is this ok [y/d/N]: y
Downloading packages:
Traceback (most recent call last):
  File "/usr/bin/yum", line 29, in <module>
    yummain.user_main(sys.argv[1:], exit_code=True)
  File "/usr/share/yum-cli/yummain.py", line 367, in user_main
    errcode = main(args)
  File "/usr/share/yum-cli/yummain.py", line 273, in main
    return_code = base.doTransaction()
  File "/usr/share/yum-cli/cli.py", line 669, in doTransaction
    problems = self.downloadPkgs(downloadpkgs, callback_total=self.download_callback_total_cb) 
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 2399, in downloadPkgs
    self.plugins.run('predownload', pkglist=pkglist)
  File "/usr/lib/python2.7/site-packages/yum/plugins.py", line 188, in run
    func(conduitcls(self, self.base, conf, **kwargs))
  File "/usr/lib/yum-plugins/axelget.py", line 523, in predownload_hook
    conduit.info(2, "Skip local Site: %s" % url)
NameError: global name 'conduct' is not defined
```

But when i disable axelget plugins i didn't get any error.

**Comment by crook** [comment]
duplicated with issue #8
